[workspace]
authors = ["Christopher T. Lee <ctlee@ucsd.edu>"]
channels = ["conda-forge"]
name = "asyn-phase-binding-data"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "*"
tqdm = ">=4.67.1,<5"
pandas = ">=2.3.3,<3"
numpy = ">=2.3.5,<3"
mdanalysis = ">=2.10.0,<3"
ffmpeg = ">=8.0.1,<9"
scipy = ">=1.16.3,<2"
imagemagick = ">=7.1.2_13,<8"
black = ">=26.1.0,<27"

[pypi-dependencies]
ctleelab_plothelper = { git = "https://github.com/ctleelab/ctleelab-mpl-utilities.git", branch = "development"}
